language: php
php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.17

before_script:
  - composer install --dev

script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/easy-extends/2-0/travis
